name: archetypal
channels:
  - conda-forge
dependencies:
  - geopandas
  - networkx
  - six
  - matplotlib>=2.1
  - requests>=2.18
  - pycountry
  - scikit-learn
  - scipy
  - pandas>=0.24
  - numpy>=1.17
  - tqdm
  - tabulate
  - path.py
  - pyomo
  - pint
  - click
  - outdated
  - opyplus
  - pip
  - pip:
    - tsam
    - deprecation
    - sigfig
    - pqdm
    - -r file:requirements-dev.txt